import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Grid,GridItem,Button} from '@chakra-ui/react'


export default function Home() {
  return (
  <Grid h="100px" templateRows="repeat(2, 1fr)"
  templateColumns="repeat(5, 1fr)" gap={10}>
  <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GridItem colSpan={2} bg="teal" >
        <h1>SeTEAM</h1>
      </GridItem>
      <GridItem colSpan={10} bg="teal" >
      </GridItem>
    </div>
    
  <GridItem colSpan={4} bg="tomato" >
    <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/signin">Sinau.id !</a>
        </h1>        <br/><br/><br/>
        <h3>Learn Everything You Need Here</h3>
        <a href="/signup"> <Button className={styles.btnColor}  >
        <h4>Sign Up For Free</h4>
          </Button></a>

<br/><br/>

        <h4> Already Have an Account ? Please Login here !</h4>
         
         <a href="/signin">
          <Button className={styles.btnColor}>
          <h4>Log in </h4>
          </Button>
          </a>
<br/><br/>
         <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
     </main>
    
  </GridItem>

</Grid>
  )
}
