name: Code Coverage
on:
  push:

jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
